name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: nix
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          nix build
          mkdir output && cp -r result/* output/

      - name: Upload artifact
        uses: https://code.forgejo.org/forgejo/upload-artifact@v4
        with:
          name: site
          path: output

  deploy:
    runs-on: deploy
    needs: build
    steps:
      - name: Get Artifacts
        uses: https://code.forgejo.org/forgejo/download-artifact@v4
        with:
          name: site
          path: output

      - name: Deploy
        uses: actions/deploy@main
        with:
          path: output/
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          deploy_user: ${{ vars.SSH_USER }}
          host: nkoll.de
          target_path: /var/www/nkoll.de/
